- name: Install dependencies
  ansible.builtin.apt:
    name:
      - pinentry-curses
      - pinentry-gnome3
  become: true

- name: Place $HOME/.gnupg/gpg-agent.conf
  ansible.builtin.copy:
    src: gpg-agent.conf
    dest: $HOME/.gnupg/gpg-agent.conf

- name: Place $HOME/.gnupg/gpg.conf
  ansible.builtin.copy:
    src: gpg.conf
    dest: $HOME/.gnupg/gpg.conf

- name: "bash : Add block to bash_profile"
  blockinfile:
    path: "{{ bash_profile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export GPG_TTY=$(tty)

- name: "zsh : Add block to zsh_zprofile"
  blockinfile:
    path: "{{ zsh_zprofile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export GPG_TTY=$(tty)
