- name: Integrate into bash
  ansible.builtin.blockinfile:
    path: "{{ bash_bashrc_top }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export GPG_TTY=$(tty)


- name: Integrate into zsh
  ansible.builtin.blockinfile:
    path: "{{ zsh_zshrc_interactive }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export GPG_TTY=$(tty)
