- name: Install
  community.general.homebrew:
    name: terraform
    path: "{{ homebrew_path }}"

- name: Create .terraformrc
  ansible.builtin.copy:
    dest: ~/.terraformrc
    content: |
      plugin_cache_dir = "$HOME/.cache/terraform-plugin-cache"

- name: Create plugin cache dir
  file:
    path: ~/.cache/terraform-plugin-cache
    state: directory

- name: Set facts
  ansible.builtin.set_fact:
    terraform_aliases:
      - word: tf
        subst: terraform

- name: "bash : bash_bashrc : Integration"
  blockinfile:
    path: "{{ bash_bashrc }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      {% for alias in terraform_aliases %}
      alias {{ alias.word }}="{{ alias.subst }}"
      {% endfor %}
  changed_when: false

- name: "zsh : zsh_zshrc : Integration"
  blockinfile:
    path: "{{ zsh_zshrc }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      {% for alias in terraform_aliases %}
      alias {{ alias.word }}="{{ alias.subst }}"
      {% endfor %}
  changed_when: false
