- name: Install Terraform
  community.general.homebrew:
    name:  terraform
    path: "{{ homebrew_path }}"

- name: Install related apps
  community.general.homebrew:
    name:
      - terragrunt # https://github.com/gruntwork-io/terragrunt
      - tflint # https://github.com/terraform-linters/tflint
      - tfsec # https://github.com/aquasecurity/tfsec
    path: "{{ homebrew_path }}"

- name: Create .terraformrc
  ansible.builtin.copy:
    dest: ~/.terraformrc
    content: |
      plugin_cache_dir = "$HOME/.cache/terraform-plugin-cache"

- name: Create plugin cache dir
  file:
    path: ~/.cache/terraform-plugin-cache
    state: directory

- name: "bash : bash_bashrc : Integration"
  blockinfile:
    path: "{{ bash_bashrc }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      alias tf=terraform

- name: "bash : bash_completion : Integration"
  blockinfile:
    path: "{{ bash_completion }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      complete -C terraform terraform

- name: "zsh : zsh_zshrc : Integration"
  blockinfile:
    path: "{{ zsh_zshrc }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      alias tf=terraform

- name: "zsh : zsh_zshrc_compinit_post : Integration"
  blockinfile:
    path: "{{ zsh_zshrc_compinit_post }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      complete -C terraform terraform
