- name: "bash : Integration"
  blockinfile:
    path: "{{ bash_profile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      wsl.exe -d wsl-vpnkit service wsl-vpnkit start || true

- name: "zsh : Integration"
  blockinfile:
    path: "{{ zsh_zprofile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      wsl.exe -d wsl-vpnkit service wsl-vpnkit start || true

- name: Start
  ansible.builtin.shell: |
    wsl.exe -d wsl-vpnkit service wsl-vpnkit start || true
  args: { executable: "{{ bash_executable }}" }
