- ansible.builtin.set_fact:
    systemd_environmentd_core: $HOME/.config/environment.d/10-core.conf

- name: Create directory {{ systemd_environmentd_core | dirname }}
  ansible.builtin.file:
    state: directory
    path: "{{ systemd_environmentd_core | dirname }}"

- name: Place skeleton {{ systemd_environmentd_core }}
  ansible.builtin.blockinfile:
    path: "{{ systemd_environmentd_core }}"
    create: true
    insertbefore: BOF
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      SYSTEMD_ENVIRONMENTD_ACTIVE=1

- name: Validate environment can be generated
  ansible.builtin.shell:
    cmd: |
      set -euo pipefail
      environment=$(/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator)
      if [[ "$environment" != "SYSTEMD_ENVIRONMENTD_ACTIVE=1" ]]; then exit 1; fi
    executable: /usr/bin/bash
  changed_when: false
