- name: Set facts
  ansible.builtin.set_fact:
    xdg_cache_home: $HOME/.cache
    xdg_config_home: $HOME/.config
    xdg_data_home: $HOME/.local/share
    xdg_exe_dir: $HOME/.local/bin
    xdg_state_home: $HOME/.local/state

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: u=rwx,g=rx,o=rx
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - "{{ xdg_cache_home }}"
    - "{{ xdg_config_home }}"
    - "{{ xdg_data_home }}"
    - "{{ xdg_exe_dir }}"
    - "{{ xdg_state_home }}"
