- name: Import role trallnag.awscli
  ansible.builtin.import_role:
    name: trallnag.awscli
  vars:
    awscli_version: "2.15.41"
    awscli_ssm_version: "1.2.553.0"

- name: Add block to { bash_bashrc }
  ansible.builtin.blockinfile:
    path: "{{ bash_bashrc }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      complete -C /usr/local/bin/aws_completer aws

- name: Add block to { zsh_zshrc_compinit_post }
  ansible.builtin.blockinfile:
    path: "{{ zsh_zshrc_compinit_post }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      complete -C /usr/local/bin/aws_completer aws
