- name: Get installed extensions
  ansible.builtin.shell: code --list-extensions
  register: task
  changed_when: false

- name: Set facts
  ansible.builtin.set_fact:
    vs_code_installed_extensions: "{{ task.stdout }}"

- name: Install extensions
  ansible.builtin.shell: |
    if ! echo "{{ vs_code_installed_extensions }}" | grep -q "{{ item }}"; then
      code --install-extension "{{ item }}"
      echo status=changed
    fi
  register: task
  changed_when: "'status=changed' in task.stdout"
  loop:
    - EditorConfig.EditorConfig
    - GitHub.vscode-pull-request-github
    - Tyriar.sort-lines
    - VisualStudioExptTeam.vscodeintellicode
    - bungcip.better-toml
    - eamodio.gitlens
    - formulahendry.code-runner
    - mhutchie.git-graph
    - ms-python.python
    - naumovs.color-highlight
    - oderwat.indent-rainbow
    - redhat.ansible
    - redhat.vscode-yaml
    - yzhang.markdown-all-in-one
