- name: Set data dir fact
  ansible.builtin.set_fact:
    windows_wsl_utilities_data_dir: "{{ xdg_data_home_dir_path }}/windows-wsl-utilities"

- name: Create data dir
  ansible.builtin.file:
    path: "{{ windows_wsl_utilities_data_dir }}"
    state: directory
    mode: u=rwx,g=,o=

- name: Checkout repository
  ansible.builtin.git:
    repo: https://github.com/wslutilities/wslu.git
    dest: "{{windows_wsl_utilities_data_dir }}/wslutilities-wslu"
    version: 3dabbee85c64b9e09d3fb266fa96676d2e76c31f
    force: true

- name: Run make target default
  ansible.builtin.command:
    chdir: "{{windows_wsl_utilities_data_dir }}/wslutilities-wslu"
    cmd: make
  changed_when: false

- name: Run make target install
  ansible.builtin.command:
    chdir: "{{windows_wsl_utilities_data_dir }}/wslutilities-wslu"
    cmd: make install
  changed_when: false
  become: true

- name: Check executable
  ansible.builtin.command:
    cmd: wslvar --version
  changed_when: false
