- name: Set fact gnupg_bridge_version
  ansible.builtin.set_fact:
    gnupg_bridge_version: "0.1.1"

- name: Set miscellaneous facts
  ansible.builtin.set_fact:
    gnupg_bridge_win_exe: "{{ win_home }}/Software/GnuPG Bridge/v{{ gnupg_bridge_version }}/gpg-bridge.exe"

- name: Check gpg-bridge.exe exists
  ansible.builtin.stat:
    path: "{{ gnupg_bridge_win_exe }}"
  failed_when: false
  register: gpg_bridge_exe_stat

- name: Create directory software
  when: not gpg_bridge_exe_stat.stat.exists
  ansible.builtin.file:
    state: directory
    path: "{{ gnupg_bridge_win_exe | dirname }}"
    mode: u=rwx,g=,o=

- name: Create temporary directory
  when: not gpg_bridge_exe_stat.stat.exists
  ansible.builtin.tempfile:
    state: directory
  register: temp_dir

- name: Download archive
  when: not gpg_bridge_exe_stat.stat.exists
  ansible.builtin.get_url:
    url: "https://github.com/BusyJay/gpg-bridge/releases/download/v{{ gnupg_bridge_version }}/gpg-bridge-v{{ gnupg_bridge_version }}.zip"
    dest: "{{ temp_dir.path }}/gpg-bridge.zip"
    mode: u=rw,g=,o=

- name: Unzip archive
  when: not gpg_bridge_exe_stat.stat.exists
  ansible.builtin.unarchive:
    src: "{{ temp_dir.path }}/gpg-bridge.zip"
    dest: "{{ gnupg_bridge_win_exe | dirname }}"
    remote_src: true

- name: Allow execution
  when: not gpg_bridge_exe_stat.stat.exists
  ansible.builtin.file:
    path: "{{ gnupg_bridge_win_exe }}"
    mode: u=rwx,g=,o=

- name: Validate gpg-bridge.exe exists
  ansible.builtin.stat:
    path: "{{ gnupg_bridge_win_exe }}"

- name: Set up systemd unit gnupg-bridge.service
  ansible.builtin.include_role:
    name: trallnag.systemd_unit
  vars:
    systemd_unit_name: gnupg-bridge.service
    systemd_unit_content: "{{ lookup('ansible.builtin.template', 'gnupg-bridge.service') }}"
    systemd_unit_activate: true
    systemd_unit_running_check: true
    systemd_unit_running_check_delay: "3"

- name: Validate that symlink exists
  ansible.builtin.stat:
    path: /etc/systemd/system/multi-user.target.wants/gnupg-bridge.service
  changed_when: false
