- name: Set directory facts
  ansible.builtin.set_fact:
    shell_login_bash: $HOME/.config/shell/login.bash
    shell_login_fish: $HOME/.config/shell/login.fish
    shell_login_zsh: $HOME/.config/shell/login.zsh

- name: Create rc files
  ansible.builtin.shell: |
    mkdir -p $HOME/.config/shell
    >> {{ shell_login_bash }}
    >> {{ shell_login_fish }}
    >> {{ shell_login_zsh }}
  changed_when: false

- name: Add block to shell_login_bash
  ansible.builtin.blockinfile:
    path: "{{ shell_login_bash }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    insertbefore: BOF
    block: "{{ lookup('ansible.builtin.template', 'login.bash') }}"

- name: Add block to shell_login_fish
  ansible.builtin.blockinfile:
    path: "{{ shell_login_fish }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    insertbefore: BOF
    block: "{{ lookup('ansible.builtin.template', 'login.fish') }}"

- name: Add block to shell_login_zsh
  ansible.builtin.blockinfile:
    path: "{{ shell_login_zsh }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    insertbefore: BOF
    block: "{{ lookup('ansible.builtin.template', 'login.zsh') }}"
