- name: Set config directory fact
  ansible.builtin.set_fact:
    shell_config_dir: "{{ xdg_config_home_dir }}/shell"

- name: Set login file facts
  ansible.builtin.set_fact:
    shell_bash_login_file: "{{ shell_config_dir }}/login.bash"
    shell_fish_login_file: "{{ shell_config_dir }}/login.fish"
    shell_zsh_login_file: "{{ shell_config_dir }}/login.zsh"

- name: Create config directory
  ansible.builtin.file:
    path: "{{ shell_config_dir }}"
    state: directory
    mode: u=rwx,g=,o=

- name: Touch login files
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: u=rw,g=,o=
    modification_time: preserve
    access_time: preserve
  loop:
    - "{{ shell_bash_login_file }}"
    - "{{ shell_fish_login_file }}"
    - "{{ shell_zsh_login_file }}"

- name: Set up environment in Bash
  ansible.builtin.blockinfile:
    path: "{{ shell_bash_login_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    insertbefore: BOF
    block: "{{ lookup('ansible.builtin.template', 'login.bash') }}"

- name: Set up environment in Fish
  ansible.builtin.blockinfile:
    path: "{{ shell_fish_login_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    insertbefore: BOF
    block: "{{ lookup('ansible.builtin.template', 'login.fish') }}"

- name: Set up environment in Zsh
  ansible.builtin.blockinfile:
    path: "{{ shell_zsh_login_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    insertbefore: BOF
    block: "{{ lookup('ansible.builtin.template', 'login.zsh') }}"
