- name: Set Homebrew prefix fact
  ansible.builtin.set_fact:
    homebrew_prefix: /home/linuxbrew/.linuxbrew

- name: Set Homebrew path fact
  ansible.builtin.set_fact:
    homebrew_path: "{{ homebrew_prefix }}/bin"

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - build-essential
      - curl
      - file
      - git
      - procps
  become: true

- name: Install
  ansible.builtin.shell:
    executable: /usr/bin/bash
    cmd: "{{ lookup('ansible.builtin.template', 'install.bash') }}"
  register: homebrew_install
  changed_when: "'status=changed' in homebrew_install.stdout"

#
# ------------------------------------------------------------------------------
#

- name: Set up environment in Bash
  ansible.builtin.blockinfile:
    path: "{{ bash_profile }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      eval "$({{ homebrew_path }}/brew shellenv)"
      export HOMEBREW_PREFIX="{{ homebrew_prefix }}"

- name: Set up completion in Bash
  ansible.builtin.blockinfile:
    path: "{{ bash_bashrc }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} completion"
    block: |
      source "$HOMEBREW_PREFIX/etc/bash_completion.d/"*

#
# ------------------------------------------------------------------------------
#

- name: Set up environment in Zsh
  ansible.builtin.blockinfile:
    path: "{{ zsh_zprofile }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      eval "$({{ homebrew_path }}/brew shellenv)"
      export HOMEBREW_PREFIX="{{ homebrew_prefix }}"

- name: Set up completion in Zsh
  ansible.builtin.blockinfile:
    path: "{{ zsh_zshrc_compinit_pre }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} completion"
    block: |
      FPATH="$HOMEBREW_PREFIX/share/zsh/site-functions:$FPATH"
