- name: Set fact
  ansible.builtin.set_fact:
    homebrew_path: /home/linuxbrew/.linuxbrew/bin

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - $HOME/.local/bin

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - build-essential
      - procps
      - curl
      - file
      - git
  become: true

- name: Install
  ansible.builtin.shell: |
    if ! test -d /home/linuxbrew/.linuxbrew; then
      if ! sudo -n true; then
        echo "Sudo requires password"
        exit 1
      fi
      unset INTERACTIVE && export NONINTERACTIVE=1
      bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      echo status=changed
    fi
  register: task
  changed_when: "'status=changed' in task.stdout"


# ------------------------------------------------------------------------------
# Environment.


- name: "bash : Add environment integration to bash_profile"
  blockinfile:
    path: "{{ bash_profile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: environment"
    block: |
      eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      export HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew

- name: "zsh : Add environment integration to zsh_zprofile"
  blockinfile:
    path: "{{ zsh_zprofile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: environment"
    block: |
      eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      export HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew


# ------------------------------------------------------------------------------
# Completion.


- name: "bash : Add completion integration to bash_bashrc"
  blockinfile:
    path: "{{ bash_bashrc }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: completion"
    block: |
      if type brew &>/dev/null; then
        if [[ -r "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh" ]]; then
          source "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh"
        else
          for COMPLETION in "$HOMEBREW_PREFIX/etc/bash_completion.d/"*; do
            [[ -r "$COMPLETION" ]] && source "$COMPLETION"
          done
          unset COMPLETION
        fi
      fi

- name: "zsh : Add completion integration to zsh_zshrc_compinit_pre"
  blockinfile:
    path: "{{ zsh_zshrc_compinit_pre }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: completion"
    block: |
      FPATH="$HOMEBREW_PREFIX/share/zsh/site-functions:$FPATH"


# ------------------------------------------------------------------------------


- name: Set fact used for deduplication
  set_fact: "{{ role_name }}_done=1"
