- name: Set fact
  ansible.builtin.set_fact:
    homebrew_path: /home/linuxbrew/.linuxbrew/bin

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - $HOME/.local/bin

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - build-essential
      - procps
      - curl
      - file
      - git
  become: true

- name: Install
  ansible.builtin.shell: |
    if ! test -d /home/linuxbrew/.linuxbrew; then
      if ! sudo -n true; then
        echo "Sudo requires password"
        exit 1
      fi
      unset INTERACTIVE && export NONINTERACTIVE=1
      bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      echo status=changed
    fi
  register: task
  changed_when: "'status=changed' in task.stdout"


# ------------------------------------------------------------------------------


- name: Set up for trallnag
  ansible.builtin.import_tasks: setup.yaml
  become_user: trallnag
  become: true
  vars:
    user: trallnag

- name: Set up for root
  ansible.builtin.import_tasks: setup.yaml
  become_user: root
  become: true
  vars:
    user: root


# ------------------------------------------------------------------------------


- name: Set fact used for deduplication
  set_fact: "{{ role_name }}_done=1"
