- name: "{{ user }} : bash : Add environment integration to bash_profile"
  blockinfile:
    path: "{{ bash_profile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: environment"
    block: |
      eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      export HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew

- name: "{{ user }} : zsh : Add environment integration to zsh_zprofile"
  blockinfile:
    path: "{{ zsh_zprofile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: environment"
    block: |
      eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      export HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew


# ------------------------------------------------------------------------------


- name: "{{ user }} : bash : Add completion integration to bash_bashrc"
  blockinfile:
    path: "{{ bash_bashrc }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: completion"
    block: |
      if type brew &>/dev/null; then
        if [[ -r "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh" ]]; then
          source "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh"
        else
          for COMPLETION in "$HOMEBREW_PREFIX/etc/bash_completion.d/"*; do
            [[ -r "$COMPLETION" ]] && source "$COMPLETION"
          done
          unset COMPLETION
        fi
      fi

- name: "{{ user }} : zsh : Add completion integration to zsh_zshrc_compinit_pre"
  blockinfile:
    path: "{{ zsh_zshrc_compinit_pre }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: completion"
    block: |
      FPATH="$HOMEBREW_PREFIX/share/zsh/site-functions:$FPATH"
