- name: Install
  community.general.homebrew:
    name: ripgrep
    path: "{{ homebrew_path }}"
  become_user: brewmaster
  become: true

- name: Link to /usr/local/bin
  ansible.builtin.file:
    src: "{{ homebrew_path }}/{{ item }}"
    dest: /usr/bin/{{ item }}
    state: link
    mode: u=rwx,g=rx,o=rx
    owner: root
    group: root
  become: true
  loop:
    - rg

#
# ------------------------------------------------------------------------------
#

- name: Set facts
  ansible.builtin.set_fact:
    ripgrep_config: "{{ xdg_config_home }}/ripgrep/ripgrep.conf"

- name: Create config directory
  ansible.builtin.file:
    state: directory
    path: "{{ ripgrep_config | dirname }}"
    mode: u=rwx,g=,o=

- name: Place config file
  ansible.builtin.copy:
    src: ripgrep.conf
    dest: "{{ ripgrep_config }}"

- name: Add block to { bash_profile }
  ansible.builtin.blockinfile:
    path: "{{ bash_profile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: 018f1661-6ae1-72e2-882f-f501ab2b6e07"
    block: |
      export RIPGREP_CONFIG_PATH="{{ ripgrep_config }}"

- name: Add block to { zsh_zprofile }
  ansible.builtin.blockinfile:
    path: "{{ zsh_zprofile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: 018f1661-a118-7ab2-96bb-25d3f58c06e5"
    block: |
      export RIPGREP_CONFIG_PATH="{{ ripgrep_config }}"
