- name: Set facts
  ansible.builtin.set_fact:
    ripgrep_config_path: $HOME/.config/ripgrep/ripgrep.conf

- name: Install
  community.general.homebrew:
    name: ripgrep
    path: "{{ homebrew_path }}"

- name: Create directory
  ansible.builtin.shell: |
    mkdir -p {{ ripgrep_config_path | dirname }}
  changed_when: false

- name: Place config
  ansible.builtin.copy:
    src: ripgrep.conf
    dest: "{{ ripgrep_config_path }}"

- name: "bash : Integration"
  blockinfile:
    path: "{{ bash_profile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export RIPGREP_CONFIG_PATH={{ ripgrep_config_path }}
  changed_when: false

- name: "zsh : Integration"
  blockinfile:
    path: "{{ zsh_zprofile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export RIPGREP_CONFIG_PATH={{ ripgrep_config_path }}
  changed_when: false
