- name: Install
  community.general.homebrew:
    name: ripgrep
    path: "{{ homebrew_path }}"

- name: Set fact ripgrep_config_home
  ansible.builtin.set_fact:
    ripgrep_config_home: "{{ xdg_config_home }}/ripgrep"

- name: Set fact ripgrep_config
  ansible.builtin.set_fact:
    ripgrep_config: "{{ ripgrep_config_home }}/ripgrep.conf"

- name: Create config directory
  ansible.builtin.file:
    state: directory
    path: "{{ ripgrep_config_home }}"
    mode: u=rwx,g=rwx,o=rx

- name: Place config file
  ansible.builtin.copy:
    src: ripgrep.conf
    dest: "{{ ripgrep_config }}"
    mode: u=rw,g=rw,o=r

- name: Make rg aware of conf in bash
  ansible.builtin.blockinfile:
    path: "{{ bash_profile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export RIPGREP_CONFIG_PATH="{{ ripgrep_config }}"

- name: Make rg aware of conf in zsh
  ansible.builtin.blockinfile:
    path: "{{ zsh_zprofile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export RIPGREP_CONFIG_PATH="{{ ripgrep_config }}"
