- name: Install
  community.general.homebrew:
    name: ripgrep
    path: "{{ homebrew_path }}"

- name: Set config home fact
  ansible.builtin.set_fact:
    ripgrep_config_home: "{{ xdg_config_home }}/ripgrep"

- name: Set config fact
  ansible.builtin.set_fact:
    ripgrep_config: "{{ ripgrep_config_home }}/ripgrep.conf"

- name: Create config directory
  ansible.builtin.file:
    state: directory
    path: "{{ ripgrep_config_home }}"
    mode: u=rwx,g=,o=

- name: Place config file
  ansible.builtin.copy:
    src: ripgrep.conf
    dest: "{{ ripgrep_config }}"
    mode: u=rw,g=,o=

- name: Set up environment in Bash
  ansible.builtin.blockinfile:
    path: "{{ bash_profile }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export RIPGREP_CONFIG_PATH="{{ ripgrep_config }}"

- name: Set up environment in Zsh
  ansible.builtin.blockinfile:
    path: "{{ zsh_zprofile }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export RIPGREP_CONFIG_PATH="{{ ripgrep_config }}"
