- name: "{{ user }} : Create directory"
  ansible.builtin.shell: |
    mkdir -p {{ ripgrep_config | dirname }}
  changed_when: false

- name: "{{ user }} : Place config"
  ansible.builtin.copy:
    src: ripgrep.conf
    dest: "{{ ripgrep_config }}"

- name: "{{ user }} : bash : Add integration to bash_profile"
  blockinfile:
    path: "{{ bash_profile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export RIPGREP_CONFIG_PATH={{ ripgrep_config }}

- name: "{{ user }} : zsh : Add integration to zsh_zprofile"
  blockinfile:
    path: "{{ zsh_zprofile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export RIPGREP_CONFIG_PATH={{ ripgrep_config }}
