- name: Install
  community.general.homebrew:
    name: bat
    path: "{{ homebrew_path }}"

- name: Set fact bat_config_home
  ansible.builtin.set_fact:
    bat_config_home: "{{ xdg_config_home }}/bat"

- name: Set fact bat_config
  ansible.builtin.set_fact:
    bat_config: "{{ bat_config_home }}/bat.conf"

- name: Create config directory
  ansible.builtin.file:
    state: directory
    path: "{{ bat_config_home }}"
    mode: u=rwx,g=,o=
    group: "{{ ansible_user }}"

- name: Place config file
  ansible.builtin.copy:
    src: bat.conf
    dest: "{{ bat_config }}"
    mode: u=rw,g=rw,o=r

- name: Add block to { shell_bash_login }
  ansible.builtin.blockinfile:
    path: "{{ shell_bash_login }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export BAT_CONFIG_PATH="{{ bat_config }}"

- name: Add block to { shell_zsh_login }
  ansible.builtin.blockinfile:
    path: "{{ shell_zsh_login }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export BAT_CONFIG_PATH="{{ bat_config }}"
