- name: Set facts
  ansible.builtin.set_fact:
    bat_config: $HOME/.config/bat/bat.conf

- name: Install
  community.general.homebrew:
    name: bat
    path: "{{ homebrew_path }}"


# ------------------------------------------------------------------------------


- name: Set up for trallnag
  ansible.builtin.import_tasks: setup.yaml
  become_user: trallnag
  become: true
  vars:
    user: trallnag

- name: Set up for root
  ansible.builtin.import_tasks: setup.yaml
  become_user: root
  become: true
  vars:
    user: root


# ------------------------------------------------------------------------------


- name: Set fact used for deduplication
  set_fact: "{{ role_name }}_done=1"
