- name: "{{ user }} : Create directory"
  ansible.builtin.shell: |
    mkdir -p {{ bat_config | dirname }}
  changed_when: false

- name: "{{ user }} : Place config"
  ansible.builtin.copy:
    src: bat.conf
    dest: "{{ bat_config }}"

- name: "{{ user }} : bash : Add integration to bash_profile"
  blockinfile:
    path: "{{ bash_profile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export BAT_CONFIG_PATH={{ bat_config }}

- name: "{{ user }} : zsh : Add integration to zsh_zprofile"
  blockinfile:
    path: "{{ zsh_zprofile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export BAT_CONFIG_PATH={{ bat_config }}
