- name: Tap repository
  community.general.homebrew_tap:
    name: weaveworks/tap
    path: "{{ homebrew_exe_dir_path }}"

- name: Install formula
  community.general.homebrew:
    name: eksctl
    path: "{{ homebrew_exe_dir_path }}"
