- name: Tap repository
  community.general.homebrew_tap:
    name: weaveworks/tap
    path: "{{ homebrew_exe_dir }}"

- name: Install formula
  community.general.homebrew:
    name: weaveworks/tap/eksctl
    path: "{{ homebrew_exe_dir }}"
