- name: Set facts
  ansible.builtin.set_fact:
    pipx_default_python: /usr/bin/python
    pipx_exe: /usr/local/bin/pipx

- name: Upgrade
  ansible.builtin.shell:
    cmd: |
      set -euxo pipefail

      /usr/bin/pip install --break-system-packages --upgrade pipx
    executable: /bin/bash
  become: true
  register: task
  changed_when: '"Requirement already satisfied" not in task.stdout'

#
# ------------------------------------------------------------------------------
# Set up environment.
#

- name: Integrate into bash
  ansible.builtin.blockinfile:
    path: "{{ bash_profile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: f52656cc-e50c-4aee-8407-08ba3f299c98"
    block: |
      export PIPX_DEFAULT_PYTHON="{{ pipx_default_python }}"

- name: Integrate into zsh
  ansible.builtin.blockinfile:
    path: "{{ zsh_zprofile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: 78b737ab-ccbe-4310-9a5c-61cf7c09432a"
    block: |
      export PIPX_DEFAULT_PYTHON="{{ pipx_default_python }}"

#
# ------------------------------------------------------------------------------
# Set up completion.
#

- name: Enable completion in bash
  ansible.builtin.blockinfile:
    path: "{{ bash_bashrc }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: 3facb34e-853b-4bb5-a7ce-5527181ab9b3"
    block: |
      if command -v register-python-argcomplete &> /dev/null; then
        eval "$(register-python-argcomplete pipx)"
      else
        eval "$(register-python-argcomplete3 pipx)"
      fi

- name: Enable completion in zsh
  ansible.builtin.blockinfile:
    path: "{{ zsh_zshrc_compinit_post }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: 4a5883e7-a7e3-41c4-8c98-fd61647f3920"
    block: |
      if command -v register-python-argcomplete &> /dev/null; then
        eval "$(register-python-argcomplete pipx)"
      else
        eval "$(register-python-argcomplete3 pipx)"
      fi

#
# ------------------------------------------------------------------------------
# Install packages.
#

- name: Install packages
  community.general.pipx:
    name: "{{ item }}"
    executable: "{{ pipx_exe }}"
  loop:
    - bpython # https://github.com/bpython/bpython
    - cookiecutter # https://github.com/cookiecutter/cookiecutter
    - copier # https://github.com/copier-org/copier
    - pre-commit # https://github.com/pre-commit/pre-commit
