- name: Set facts
  ansible.builtin.set_fact:
    pipx_default_python: /usr/bin/python3
    pipx_executable: /usr/bin/pipx

# ------------------------------------------------------------------------------
# Install Pipx.

- name: Install dependencies with APT
  ansible.builtin.apt:
    name:
      - pipx
      - python-is-python3
  become: true

# ------------------------------------------------------------------------------
# Setup environment.

- name: "bash : Add block to bash_profile"
  ansible.builtin.blockinfile:
    path: "{{ bash_profile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      #export PIPX_DEFAULT_PYTHON={{ pipx_default_python }}

- name: "zsh : Add block to zsh_zprofile"
  ansible.builtin.blockinfile:
    path: "{{ zsh_zprofile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      #export PIPX_DEFAULT_PYTHON={{ pipx_default_python }}

# ------------------------------------------------------------------------------
# Setup completions.

- name: "bash : Add block to bash_profile"
  ansible.builtin.blockinfile:
    path: "{{ bash_bashrc }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      #source "$HOME/.local/pipx/venvs/argcomplete/lib/python3.10/site-packages/argcomplete/bash_completion.d/_python-argcomplete"
      if command -v register-python-argcomplete &> /dev/null; then
        eval "$(register-python-argcomplete pipx)"
      else
        eval "$(register-python-argcomplete3 pipx)"
      fi

- name: "zsh : Add block to zsh_zshrc_compinit_post"
  ansible.builtin.blockinfile:
    path: "{{ zsh_zshrc_compinit_post }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      #fpath=( $HOME/.local/pipx/venvs/argcomplete/lib/python3.10/site-packages/argcomplete/bash_completion.d "${fpath[@]}" )
      if command -v register-python-argcomplete &> /dev/null; then
        eval "$(register-python-argcomplete pipx)"
      else
        eval "$(register-python-argcomplete3 pipx)"
      fi

# ------------------------------------------------------------------------------
# Install packages with Pipx.

- name: Install packages
  community.general.pipx:
    name: "{{ item }}"
    executable: "{{ pipx_executable }}"
  loop:
    - bpython # https://github.com/bpython/bpython
    - pre-commit # https://github.com/pre-commit/pre-commit
