- name: Install
  community.general.homebrew:
    name: eza
    path: "{{ homebrew_path }}"

- name: Set alias facts
  ansible.builtin.set_fact:
    eza_aliases:
      - word: es
        subst: >-
          eza
      - word: e
        subst: >-
          eza
          --all
      - word: eo
        subst: >-
          eza
          --all
          --group-directories-first
          --oneline
      - word: el
        subst: >-
          eza
          --all
          --classify
          --color-scale
          --group-directories-first
          --header
          --long
          --time-style=long-iso
      - word: ll
        subst: >-
          eza
          --all
          --classify
          --color-scale
          --group-directories-first
          --header
          --long
          --time-style=long-iso
      - word: ex
        subst: >-
          eza
          --accessed
          --all
          --binary
          --blocksize
          --color-scale
          --created
          --extended
          --group
          --header
          --inode
          --links
          --long
          --modified
          --mounts
          --time-style=long-iso
      - word: et
        subst: >-
          eza
          --all
          --group-directories-first
          --tree

- name: Set up aliases in bash
  ansible.builtin.blockinfile:
    path: "{{ bash_aliases }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }}"
    block: |
      {% for alias in eza_aliases %}
      alias {{ alias.word }}='{{ alias.subst }}'
      {% endfor %}

- name: Set up aliases in zsh
  ansible.builtin.blockinfile:
    path: "{{ zsh_aliases }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }}"
    block: |
      {% for alias in eza_aliases %}
      alias {{ alias.word }}='{{ alias.subst }}'
      {% endfor %}
