- name: Install
  community.general.homebrew:
    name: eza
    path: "{{ homebrew_path }}"
  become_user: brewmaster
  become: true

- name: Link to /usr/local/bin
  ansible.builtin.file:
    src: "{{ homebrew_path }}/{{ item }}"
    dest: /usr/bin/{{ item }}
    state: link
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  loop:
    - eza
  become: true

- name: Set facts
  ansible.builtin.set_fact:
    eza_aliases:
      - word: es
        subst: eza
      - word: e
        subst: eza -a
      - word: eo
        subst: eza -1a --group-directories-first
      - word: el
        subst: eza -ahl --time-style=long-iso --links --classify --color-scale --group-directories-first
      - word: ll
        subst: eza -ahl --time-style=long-iso --links --classify --color-scale --group-directories-first
      - word: ex
        subst: eza -lbhHigUmuSa@ --time-style=long-iso --color-scale
      - word: et
        subst: eza -aT --group-directories-first

- name: Add block to { bash_aliases }
  ansible.builtin.blockinfile:
    path: "{{ bash_aliases }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      {% for alias in eza_aliases %}
      alias {{ alias.word }}='{{ alias.subst }}'
      {% endfor %}

- name: Add integration to { zsh_aliases }
  ansible.builtin.blockinfile:
    path: "{{ zsh_aliases }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      {% for alias in eza_aliases %}
      alias {{ alias.word }}='{{ alias.subst }}'
      {% endfor %}
