- name: "{{ user }} : bash : Add integration to bash_aliases"
  blockinfile:
    path: "{{ bash_aliases }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      {% for alias in eza_aliases %}
      alias {{ alias.word }}='{{ alias.subst }}'
      {% endfor %}

- name: "{{ user }} : zsh : Add integration to zsh_aliases"
  blockinfile:
    path: "{{ zsh_aliases }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      {% for alias in eza_aliases %}
      alias {{ alias.word }}='{{ alias.subst }}'
      {% endfor %}
