- name: Set facts
  ansible.builtin.set_fact:
    wslu_data_home: "{{ xdg_data_home }}/wslu"

- name: Create directory
  ansible.builtin.file:
    path: "{{ wslu_data_home }}"
    state: directory
    mode: u=rwx,g=rwx,o=rx

- name: Checkout wslutilities/wslu
  ansible.builtin.git:
    repo: https://github.com/wslutilities/wslu.git
    dest: "{{ wslu_data_home }}/wslutilities-wslu"
    version: v4.1.3
    force: true

- name: Perform make
  ansible.builtin.command:
    chdir: "{{ wslu_data_home }}/wslutilities-wslu"
    cmd: make
  changed_when: false

- name: Perform make install
  ansible.builtin.command:
    chdir: "{{ wslu_data_home }}/wslutilities-wslu"
    cmd: make install
  changed_when: false
  become: true
