- name: Set facts
  ansible.builtin.set_fact:
    # Data related to this role is stored here.
    windows_gpg_agent_trigger_home: >-
      {{ xdg_data_home }}/windows-gpg-agent-trigger

    # Path to the connect-agent executable in Windows.
    windows_gpg_agent_trigger_exe: >-
      /mnt/c/Program Files (x86)/GnuPG/bin/gpg-connect-agent.exe

    # Path to the sentinel lock file in Windows.
    windows_gpg_agent_trigger_lock: >-
      {{ windows_home }}/AppData/Roaming/gnupg/gnupg_spawn_agent_sentinel.lock

- name: Create home directory
  ansible.builtin.file:
    state: directory
    path: "{{ windows_gpg_agent_trigger_home }}"
    mode: u=rwx,g=,o=

- name: Validate executable existence
  ansible.builtin.stat:
    path: "{{ windows_gpg_agent_trigger_exe }}"

- name: Validate executable usability
  ansible.builtin.command:
    cmd: "'{{ windows_gpg_agent_trigger_exe }}' --help"
  changed_when: false

- name: Render and place windows-gpg-agent-trigger.sh
  ansible.builtin.template:
    src: windows-gpg-agent-trigger.sh
    dest: "{{ windows_gpg_agent_trigger_home }}/windows-gpg-agent-trigger.sh"
    mode: u=rwx,g=r,o=r
  register: script

- name: Set up systemd unit windows-gpg-agent-trigger.service
  ansible.builtin.include_role:
    name: trallnag.systemd_unit
  vars:
    systemd_unit_name: windows-gpg-agent-trigger.service
    systemd_unit_activate: true
    systemd_unit_running_check: true
    systemd_unit_running_check_delay: "3"
    systemd_unit_restart: "{{ script.changed }}"
    systemd_unit_content: >-
      {{
        lookup(
          'ansible.builtin.template',
          'windows-gpg-agent-trigger.service'
        )
      }}

- name: Validate wants symlink existence
  ansible.builtin.stat:
    path: "{{ path_parts | join }}"
  vars:
    path_parts:
      - "/etc/systemd/system/multi-user.target.wants/"
      - "windows-gpg-agent-trigger.service"
