- name: Install formulae
  community.general.homebrew:
    name:
      - age # https://github.com/FiloSottile/age
      - fd # https://github.com/sharkdp/fd
      - gh
      - go # https://go.dev/doc/devel/release
      - go-task # https://taskfile.dev
      - golangci-lint # https://golangci-lint.run/
      - helm
      - hugo
      - just # https://github.com/casey/just
      - kubectx
      - kubernetes-cli
      - optipng # http://optipng.sourceforge.net/
      - shellcheck # https://github.com/koalaman/shellcheck
      - shfmt # https://github.com/mvdan/sh
      - watchexec # https://github.com/watchexec/watchexec
      - zellij
    path: "{{ homebrew_path }}"


# ------------------------------------------------------------------------------


- name: Set fact used for deduplication
  set_fact: "{{ role_name }}_done=1"
