- name: Install
  ansible.builtin.apt:
    name:
      - bash
      - bash-completion
  become: true

- import_tasks: cleanup.yaml

- import_tasks: facts.yaml

- name: Delete $HOME/.bash_profile
  ansible.builtin.file:
    path: $HOME/.bash_profile
    state: absent

- name: Place $HOME/.profile
  ansible.builtin.copy:
    src: .profile
    dest: $HOME/.profile

- name: Place $HOME/.bashrc
  ansible.builtin.copy:
    src: .bashrc
    dest: $HOME/.bashrc

- name: Place $HOME/.bash_logout
  ansible.builtin.copy:
    src: .bash_logout
    dest: $HOME/.bash_logout

- name: "bash_completion : Integration"
  ansible.builtin.blockinfile:
    path: "{{ bash_completion }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    insertbefore: BOF
    block: |
      # Bootstrap cykerway/complete-alias.
      source "$HOME/.local/complete-alias/complete_alias"
      source "$HOME/.config/complete_alias"

- name: Clone cykerway/complete-alias to $HOME/.local/complete-alias
  ansible.builtin.git:
    repo: https://github.com/cykerway/complete-alias.git
    dest: $HOME/.local/complete-alias
