- name: Set directory facts
  ansible.builtin.set_fact:
    bash_dynrc_dir: "{{ xdg_config_home }}/bash"

    bash_completions_dir: "{{ xdg_data_home }}/bash-completion/completions"

- name: Set file facts
  ansible.builtin.set_fact:
    bash_completion: "{{ xdg_config_home }}/bash_completion"

    bash_profile: "{{ bash_dynrc_dir }}/profile.bash"

    bash_bashrc_top: "{{ bash_dynrc_dir }}/bashrc-top.bash"
    bash_bashrc: "{{ bash_dynrc_dir }}/bashrc.bash"

    bash_aliases: "{{ bash_dynrc_dir }}/aliases.bash"

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: u=rwx,g=rx,o=rx
  loop:
    - "{{ bash_dynrc_dir }}"
    - "{{ bash_completions_dir }}"

- name: Create files
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: u=rw,g=,o=
    modification_time: preserve
    access_time: preserve
  loop:
    - "{{ bash_completion }}"
    - "{{ bash_profile }}"
    - "{{ bash_bashrc_top }}"
    - "{{ bash_bashrc }}"
    - "{{ bash_aliases }}"

- name: Install packages
  ansible.builtin.apt:
    name:
      - bash
      - bash-completion
  become: true

#
# ------------------------------------------------------------------------------
#

- name: Set up export of dot env vars during bash login
  ansible.builtin.blockinfile:
    path: "{{ shell_bash_login }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export DOT_BASH_COMPLETIONS_DIR="{{ bash_completions_dir }}"

      export DOT_BASH_COMPLETION="{{ bash_completion }}"

      export DOT_BASH_PROFILE="{{ bash_profile }}"

      export DOT_BASH_BASHRC_TOP="{{ bash_bashrc_top }}"
      export DOT_BASH_BASHRC="{{ bash_bashrc }}"

      export DOT_BASH_ALIASES="{{ bash_aliases }}"

- name: Set up export of dot env vars during fish login
  ansible.builtin.blockinfile:
    path: "{{ shell_fish_login }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      set -x DOT_BASH_COMPLETIONS_DIR "{{ bash_completions_dir }}"

      set -x DOT_BASH_COMPLETION "{{ bash_completion }}"

      set -x DOT_BASH_PROFILE "{{ bash_profile }}"

      set -x DOT_BASH_BASHRC_TOP "{{ bash_bashrc_top }}"
      set -x DOT_BASH_BASHRC "{{ bash_bashrc }}"

      set -x DOT_BASH_ALIASES "{{ bash_aliases }}"

- name: Set up export of dot env vars during zsh login
  ansible.builtin.blockinfile:
    path: "{{ shell_zsh_login }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export DOT_BASH_COMPLETIONS_DIR="{{ bash_completions_dir }}"

      export DOT_BASH_COMPLETION="{{ bash_completion }}"

      export DOT_BASH_PROFILE="{{ bash_profile }}"

      export DOT_BASH_BASHRC_TOP="{{ bash_bashrc_top }}"
      export DOT_BASH_BASHRC="{{ bash_bashrc }}"

      export DOT_BASH_ALIASES="{{ bash_aliases }}"

#
# ------------------------------------------------------------------------------
#

- name: Delete .bash_profile
  ansible.builtin.file:
    path: $HOME/.bash_profile
    state: absent

- name: Render and place files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "$HOME/{{ item }}"
    mode: u=rw,g=,o=
  loop:
    - .profile
    - .bashrc
    - .bash_logout
