- name: Install
  ansible.builtin.apt:
    name:
      - bash
      # Necessary for cykerway/complete-alias.
      - bash-completion
  become: true

- import_tasks: cleanup.yaml

- import_tasks: facts.yaml

- name: Delete $HOME/.bash_profile
  ansible.builtin.file:
    path: $HOME/.bash_profile
    state: absent

- name: Place $HOME/.profile
  ansible.builtin.copy:
    src: .profile
    dest: $HOME/.profile

- name: Place $HOME/.bashrc
  ansible.builtin.copy:
    src: .bashrc
    dest: $HOME/.bashrc

- name: Place $HOME/.bash_logout
  ansible.builtin.copy:
    src: .bash_logout
    dest: $HOME/.bash_logout

- name: Place {{ bash_completion }}
  ansible.builtin.copy:
    src: bash_completion.bash
    dest: "{{ bash_completion }}"
  changed_when: false

- name: Clone cykerway/complete-alias to $HOME/.local/complete-alias
  ansible.builtin.git:
    repo: https://github.com/cykerway/complete-alias.git
    dest: $HOME/.local/complete-alias
