- name: Install packages
  ansible.builtin.apt:
    name:
      - bash
      - bash-completion
  become: true

- name: Set directory facts
  ansible.builtin.set_fact:
    bash_config_dir: "{{ xdg_config_home_dir }}/bash"
    bash_completions_dir: "{{ xdg_data_home_dir }}/bash-completion/completions"

- name: Set file facts
  ansible.builtin.set_fact:
    bash_completion_file: "{{ xdg_config_home_dir }}/bash_completion"
    bash_profile_file: "{{ bash_config_dir }}/profile.bash"
    bash_bashrc_top_file: "{{ bash_config_dir }}/bashrc-top.bash"
    bash_bashrc_file: "{{ bash_config_dir }}/bashrc.bash"
    bash_aliases_file: "{{ bash_config_dir }}/aliases.bash"

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: u=rwx,g=,o=
  loop:
    - "{{ bash_config_dir }}"
    - "{{ bash_completions_dir }}"

- name: Create files
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: u=rw,g=,o=
    modification_time: preserve
    access_time: preserve
  loop:
    - "{{ bash_completion_file }}"
    - "{{ bash_profile_file }}"
    - "{{ bash_bashrc_top_file }}"
    - "{{ bash_bashrc_file }}"
    - "{{ bash_aliases_file }}"

#
# ------------------------------------------------------------------------------
#

- name: Set up environment in Bash
  ansible.builtin.blockinfile:
    path: "{{ shell_bash_login_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export DOT_BASH_CONFIG_DIR="{{ bash_config_dir }}"
      export DOT_BASH_COMPLETIONS_DIR="{{ bash_completions_dir }}"
      export DOT_BASH_COMPLETION_FILE="{{ bash_completion_file }}"
      export DOT_BASH_PROFILE_FILE="{{ bash_profile_file }}"
      export DOT_BASH_BASHRC_TOP_FILE="{{ bash_bashrc_top_file }}"
      export DOT_BASH_BASHRC_FILE="{{ bash_bashrc_file }}"
      export DOT_BASH_ALIASES_FILE="{{ bash_aliases_file }}"

- name: Set up environment in Fish
  ansible.builtin.blockinfile:
    path: "{{ shell_fish_login_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      set -x DOT_BASH_CONFIG_DIR "{{ bash_config_dir }}"
      set -x DOT_BASH_COMPLETIONS_DIR "{{ bash_completions_dir }}"
      set -x DOT_BASH_COMPLETION_FILE "{{ bash_completion_file }}"
      set -x DOT_BASH_PROFILE_FILE "{{ bash_profile_file }}"
      set -x DOT_BASH_BASHRC_TOP_FILE "{{ bash_bashrc_top_file }}"
      set -x DOT_BASH_BASHRC_FILE "{{ bash_bashrc_file }}"
      set -x DOT_BASH_ALIASES_FILE "{{ bash_aliases_file }}"

- name: Set up environment in Zsh
  ansible.builtin.blockinfile:
    path: "{{ shell_zsh_login_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ role_name }} environment"
    block: |
      export DOT_BASH_CONFIG_DIR="{{ bash_config_dir }}"
      export DOT_BASH_COMPLETIONS_DIR="{{ bash_completions_dir }}"
      export DOT_BASH_COMPLETION_FILE="{{ bash_completion_file }}"
      export DOT_BASH_PROFILE_FILE="{{ bash_profile_file }}"
      export DOT_BASH_BASHRC_TOP_FILE="{{ bash_bashrc_top_file }}"
      export DOT_BASH_BASHRC_FILE="{{ bash_bashrc_file }}"
      export DOT_BASH_ALIASES_FILE="{{ bash_aliases_file }}"

#
# ------------------------------------------------------------------------------
#

- name: Delete .bash_profile
  ansible.builtin.file:
    path: $HOME/.bash_profile
    state: absent

- name: Render and place files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "$HOME/{{ item }}"
    mode: u=rw,g=,o=
  loop:
    - .profile
    - .bashrc
    - .bash_logout
