- name: Set facts
  ansible.builtin.set_fact:
    bash_executable: /usr/bin/bash

    bash_completions_dir: $HOME/.local/share/bash-completion/completions

    bash_aliases: $HOME/.config/bash/dynrc/aliases.bash
    bash_bashrc: $HOME/.config/bash/dynrc/bashrc.bash
    bash_completion: $HOME/.config/bash_completion
    bash_profile: $HOME/.config/bash/dynrc/profile.bash

- name: Set up for trallnag
  ansible.builtin.import_tasks: setup.yaml
  become_user: trallnag
  become: true
  vars:
    user: trallnag

- name: Set up for root
  ansible.builtin.import_tasks: setup.yaml
  become_user: root
  become: true
  vars:
    user: root
