- name: "{{ user }} : Create dirs and files"
  ansible.builtin.shell: |
    mkdir -p "$HOME/.config/bash/dynrc"

    mkdir -p "{{ bash_completions_dir }}"

    >> "{{ bash_completion }}"

    >> "{{ bash_profile }}"

    >> "{{ bash_bashrc_top }}"
    >> "{{ bash_bashrc }}"

    >> "{{ bash_aliases }}"
  changed_when: false


# ------------------------------------------------------------------------------


- name: "{{ user }} : shell : Add block to {{ shell_login_bash }}"
  blockinfile:
    path: "{{ shell_login_bash }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export DOT_BASH_COMPLETIONS_DIR="{{ bash_completions_dir }}"

      export DOT_BASH_COMPLETION="{{ bash_completion }}"

      export DOT_BASH_PROFILE="{{ bash_profile }}"

      export DOT_BASH_BASHRC_TOP="{{ bash_bashrc_top }}"
      export DOT_BASH_BASHRC="{{ bash_bashrc }}"

      export DOT_BASH_ALIASES="{{ bash_aliases }}"

- name: "{{ user }} : shell : Add block to {{ shell_login_fish }}"
  blockinfile:
    path: "{{ shell_login_fish }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      set -x DOT_BASH_COMPLETIONS_DIR "{{ bash_completions_dir }}"

      set -x DOT_BASH_COMPLETION "{{ bash_completion }}"

      set -x DOT_BASH_PROFILE "{{ bash_profile }}"

      set -x DOT_BASH_BASHRC_TOP "{{ bash_bashrc_top }}"
      set -x DOT_BASH_BASHRC "{{ bash_bashrc }}"

      set -x DOT_BASH_ALIASES "{{ bash_aliases }}"

- name: "{{ user }} : shell : Add block to {{ shell_login_zsh }}"
  blockinfile:
    path: "{{ shell_login_zsh }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export DOT_BASH_COMPLETIONS_DIR="{{ bash_completions_dir }}"

      export DOT_BASH_COMPLETION="{{ bash_completion }}"

      export DOT_BASH_PROFILE="{{ bash_profile }}"

      export DOT_BASH_BASHRC_TOP="{{ bash_bashrc_top }}"
      export DOT_BASH_BASHRC="{{ bash_bashrc }}"

      export DOT_BASH_ALIASES="{{ bash_aliases }}"


# ------------------------------------------------------------------------------


- name: "{{ user }} : Delete $HOME/.bash_profile"
  ansible.builtin.file:
    path: $HOME/.bash_profile
    state: absent

- name: "{{ user }} : Place files"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "$HOME/{{ item }}"
  loop:
    - .profile
    - .bashrc
    - .bash_logout


# ------------------------------------------------------------------------------


- name: "{{ user }} : Clone cykerway/complete-alias to $HOME/.local/share/complete-alias"
  ansible.builtin.git:
    repo: https://github.com/cykerway/complete-alias.git
    dest: $HOME/.local/share/complete-alias

- name: "{{ user }} : Add block for complete-alias to {{ bash_completion }}"
  ansible.builtin.blockinfile:
    path: "{{ bash_completion }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    insertbefore: EOF
    block: |
      source $HOME/.local/share/complete-alias/complete_alias
