- name: Install
  community.general.homebrew:
    name: git-extras
    path: "{{ homebrew_path }}"

# Necessary due to caveat in formula. For some reason completion for Zsh is
# not being setup automatically. For Bash it works fine out of the box.
- name: "zsh : Add block to zsh_zshrc_compinit_post"
  ansible.builtin.blockinfile:
    path: "{{ zsh_zshrc_compinit_post }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      source /home/linuxbrew/.linuxbrew/opt/git-extras/share/git-extras/git-extras-completion.zsh

- name: Set facts
  ansible.builtin.set_fact:
    git_extras_aliases:
      - word: gitb
        subst: git browse

- name: "bash : Integration : Aliases"
  blockinfile:
    path: "{{ bash_bashrc }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: aliases"
    block: |
      {% for alias in git_extras_aliases %}
      alias {{ alias.word }}="{{ alias.subst }}"
      {% endfor %}

- name: "zsh : Integration : Aliases"
  blockinfile:
    path: "{{ zsh_zshrc }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: aliases"
    block: |
      {% for alias in git_extras_aliases %}
      alias {{ alias.word }}="{{ alias.subst }}"
      {% endfor %}
