- name: Install
  ansible.builtin.apt:
    name: git-extras
    state: present
  become: true

- name: Set facts
  ansible.builtin.set_fact:
    git_extras_aliases:
      - word: gitb
        subst: git browse

- name: Add block to { bash_aliases }
  ansible.builtin.blockinfile:
    path: "{{ bash_aliases }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      {% for alias in git_extras_aliases %}
      alias {{ alias.word }}='{{ alias.subst }}'
      {% endfor %}

- name: Add block to { zsh_aliases }
  ansible.builtin.blockinfile:
    path: "{{ zsh_aliases }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      {% for alias in git_extras_aliases %}
      alias {{ alias.word }}='{{ alias.subst }}'
      {% endfor %}
