- name: Install OpenSSH
  ansible.builtin.apt:
    name: ssh
  become: true

- name: Start and enable OpenSSH server
  ansible.builtin.systemd_service:
    name: ssh
    state: started
    enabled: true

- name: Set facts
  ansible.builtin.set_fact:
    gnupg_agent_relay_data_home: "{{ xdg_data_home }}/gnupg"

    gnupg_agent_relay_win_ssh_exe: /mnt/c/Windows/System32/OpenSSH/ssh.exe

- name: Validate ssh.exe exists
  ansible.builtin.stat:
    path: "{{ gnupg_agent_relay_win_ssh_exe }}"

- name: Create directory gnupg
  ansible.builtin.file:
    state: directory
    path: "{{ gnupg_agent_relay_data_home }}"
    mode: u=rwx,g=rwx,o=rx

- name: Render and place gnupg-agent-relay.sh
  ansible.builtin.template:
    src: gnupg-agent-relay.sh
    dest: "{{ gnupg_agent_relay_data_home }}/gnupg-agent-relay.sh"
    mode: u=rwx,g=rwx,o=r
  register: script

- name: Set up systemd unit gnupg-agent-relay.service
  ansible.builtin.include_role:
    name: systemd_unit
  vars:
    systemd_unit_name: gnupg-agent-relay.service
    systemd_unit_content: "{{ lookup('ansible.builtin.template', 'gnupg-agent-relay.service') }}"
    systemd_unit_restart: "{{ script.changed }}"
    systemd_unit_activate: true
    systemd_unit_running_check: true
    systemd_unit_running_check_delay: "3"

- name: Validate that symlink exists
  ansible.builtin.stat:
    path: /etc/systemd/system/multi-user.target.wants/gnupg-agent-relay.service
  changed_when: false
