- name: Set facts
  ansible.builtin.set_fact:
    # Data related to this role is stored here.
    windows_gpg_agent_relay_home: "{{ xdg_data_home }}/windows-gpg-agent-relay"

    # Path to the SSH executable in Windows.
    windows_gpg_agent_relay_ssh_exe: /mnt/c/Windows/System32/OpenSSH/ssh.exe

- name: Create data home directory
  ansible.builtin.file:
    state: directory
    path: "{{ windows_gpg_agent_relay_home }}"
    mode: u=rwx,g=,o=

- name: Validate executable existence
  ansible.builtin.stat:
    path: "{{ windows_gpg_agent_relay_ssh_exe }}"

- name: Validate executable usability
  ansible.builtin.command:
    cmd: "{{ windows_gpg_agent_relay_ssh_exe }} -V"
  changed_when: false

- name: Render and place windows-gpg-agent-relay.sh
  ansible.builtin.template:
    src: windows-gpg-agent-relay.sh
    dest: "{{ windows_gpg_agent_relay_home }}/windows-gpg-agent-relay.sh"
    mode: u=rwx,g=r,o=r
  register: script

- name: Set up systemd unit windows-gpg-agent-relay.service
  ansible.builtin.include_role:
    name: trallnag.systemd_unit
  vars:
    systemd_unit_name: windows-gpg-agent-relay.service
    systemd_unit_activate: true
    systemd_unit_running_check: true
    systemd_unit_running_check_delay: "3"
    systemd_unit_restart: "{{ script.changed }}"
    systemd_unit_content: >-
      {{
        lookup(
          'ansible.builtin.template',
          'windows-gpg-agent-relay.service'
        )
      }}

- name: Validate wants symlink existence
  ansible.builtin.stat:
    path: "{{ path_parts | join }}"
  vars:
    path_parts:
      - "/etc/systemd/system/multi-user.target.wants/"
      - "windows-gpg-agent-relay.service"
