- name: Install OpenSSH
  ansible.builtin.apt:
    name: ssh
  become: true

- name: Start and enable OpenSSH server
  ansible.builtin.systemd_service:
    name: ssh
    state: started
    enabled: true
  become: true

- name: Set facts
  ansible.builtin.set_fact:
    ssh_agent_relay_data_home: "{{ xdg_data_home }}/ssh"

    ssh_agent_relay_win_exe: /mnt/c/Windows/System32/OpenSSH/ssh.exe

    ssh_agent_relay_socket_dir: /run/user/{{ ansible_facts.user_uid }}/ssh
    ssh_agent_relay_socket: /run/user/{{ ansible_facts.user_uid }}/ssh/ssh-agent-relay.sock

- name: Validate ssh.exe exists
  ansible.builtin.stat:
    path: "{{ ssh_agent_relay_win_exe }}"

- name: Create directory ssh
  ansible.builtin.file:
    state: directory
    path: "{{ ssh_agent_relay_data_home }}"
    mode: u=rwx,g=,o=

- name: Render and place ssh-agent-relay.sh
  ansible.builtin.template:
    src: ssh-agent-relay.sh
    dest: "{{ ssh_agent_relay_data_home }}/ssh-agent-relay.sh"
    mode: u=rwx,g=,o=
  register: script

- name: Set up systemd unit ssh-agent-relay.service
  ansible.builtin.include_role:
    name: trallnag.systemd_unit
  vars:
    systemd_unit_name: ssh-agent-relay.service
    systemd_unit_content: "{{ lookup('ansible.builtin.template', 'ssh-agent-relay.service') }}"
    systemd_unit_restart: "{{ script.changed }}"
    systemd_unit_activate: true
    systemd_unit_running_check: true
    systemd_unit_running_check_delay: "3"

- name: Validate that symlink exists
  ansible.builtin.stat:
    path: /etc/systemd/system/multi-user.target.wants/ssh-agent-relay.service
  become: true

- name: Add block to { shell_bash_login }
  ansible.builtin.blockinfile:
    path: "{{ shell_bash_login }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export SSH_AUTH_SOCK="{{ ssh_agent_relay_socket }}"

- name: Add block to { shell_zsh_login }
  ansible.builtin.blockinfile:
    path: "{{ shell_zsh_login }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export SSH_AUTH_SOCK="{{ ssh_agent_relay_socket }}"
