- name: Install
  community.general.homebrew:
    name: volta
    path: "{{ homebrew_path }}"

- name: "bash : Add block to bash_profile"
  blockinfile:
    path: "{{ bash_profile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export VOLTA_HOME="$HOME/.volta"
      PATH="$VOLTA_HOME/bin:$PATH"

- name: "zsh : Integration"
  blockinfile:
    path: "{{ zsh_zprofile }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export VOLTA_HOME="$HOME/.volta"
      path=($VOLTA_HOME/bin $path)

- name: Install and set node@20 as default
  ansible.builtin.shell: |
    export VOLTA_HOME="$HOME/.volta"
    PATH="$VOLTA_HOME/bin:$PATH"

    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    volta install node@20
  changed_when: false

- name: Install a few tools
  ansible.builtin.shell: |
    export VOLTA_HOME="$HOME/.volta"
    PATH="$VOLTA_HOME/bin:$PATH"

    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    volta install prettier
  changed_when: false
