- name: Set facts
  ansible.builtin.set_fact:
    gpg_agent_relay_win_ssh_exe: /mnt/c/Program Files/OpenSSH/ssh.exe

- name: Get stats of { gpg_agent_relay_win_ssh_exe }
  ansible.builtin.stat:
    path: "{{ gpg_agent_relay_win_ssh_exe }}"

- name: Create directory
  ansible.builtin.file:
    path: "{{ xdg_data_home }}/gpg"
    state: directory
    mode: u=rwx,g=rx,o=rx
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Render and place gpg-agent-relay.sh
  ansible.builtin.template:
    src: gpg-agent-relay.sh
    dest: "{{ xdg_data_home }}/gpg/gpg-agent-relay.sh"
    mode: u=rwx,g=,o=
  register: script

- ansible.builtin.include_role:
    name: systemd_unit
  vars:
    systemd_unit: "{{ item }}"
    systemd_unit_content: "{{ lookup('ansible.builtin.template', item) }}"
    systemd_unit_restart: "{{ script.changed }}"
    systemd_unit_activate: true
    systemd_unit_running_check: true
    systemd_unit_running_check_delay: "1"
  loop:
    - gpg-agent-relay.service

- name: Verify that symlink exists
  ansible.builtin.stat:
    path: /etc/systemd/system/multi-user.target.wants/gpg-agent-relay.service
  changed_when: false
