- name: Install
  community.general.homebrew:
    name: fzf
    path: "{{ homebrew_path }}"

- name: Generate shell config script
  ansible.builtin.command: /home/linuxbrew/.linuxbrew/opt/fzf/install --no-update-rc --key-bindings --completion
  changed_when: false

- name: Hook into bash
  blockinfile:
    path: "{{ bash_bashrc }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      [[ -f ~/.fzf.bash ]] && source ~/.fzf.bash

- name: Hook into zsh
  blockinfile:
    path: "{{ zsh_zshrc_compinit_pre }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      [[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh
