# Remove files we don't need because our ZDOTDIR is not set to HOME.
- name: Delete files
  ansible.builtin.shell: |
    rm -rf $HOME/.zshrc
    rm -rf $HOME/.zsh_history
    rm -rf $HOME/.zcompdump
  changed_when: false

- name: Place $HOME/.zshenv
  ansible.builtin.copy:
    dest: $HOME/.zshenv
    content: ZDOTDIR=$HOME/.config/zsh

- name: Place $HOME/.config/zsh/.zshenv
  ansible.builtin.copy:
    src: .zshenv
    dest: $HOME/.config/zsh/.zshenv

- name: Place $HOME/.config/zsh/.zprofile
  ansible.builtin.copy:
    src: .zprofile
    dest: $HOME/.config/zsh/.zprofile

- name: Place $HOME/.config/zsh/.zshrc
  ansible.builtin.copy:
    src: .zshrc
    dest: $HOME/.config/zsh/.zshrc

- name: Place $HOME/.config/zsh/.zlogin
  ansible.builtin.copy:
    src: .zlogin
    dest: $HOME/.config/zsh/.zlogin

- name: Place $HOME/.config/zsh/.zlogout
  ansible.builtin.copy:
    src: .zlogout
    dest: $HOME/.config/zsh/.zlogout
