- name: "{{ user }} : Create directories"
  ansible.builtin.shell: |
    mkdir -p "$HOME/.cache/zsh"
    mkdir -p "$HOME/.config/zsh"

    mkdir -p "{{ zsh_completions_dir }}"
    mkdir -p "{{ zsh_dynrc_dir }}"
    mkdir -p "{{ zsh_functions_dir }}"
    mkdir -p "{{ zsh_scripts_dir }}"
  changed_when: false

- name: "{{ user }} : Create files"
  ansible.builtin.shell: |
    >> "{{ zsh_zprofile }}"

    >> "{{ zsh_zshrc_interactive }}"
    >> "{{ zsh_zshrc }}"
    >> "{{ zsh_zshrc_compinit_pre }}"
    >> "{{ zsh_zshrc_compinit_post }}"

    >> "{{ zsh_aliases }}"

    >> "{{ zsh_zlogin }}"

    >> "{{ zsh_zlogout }}"

    >> "{{ zsh_p10k }}"
  changed_when: false


# ------------------------------------------------------------------------------


- name: "{{ user }} : shell : Add block to shell_login_bash"
  blockinfile:
    path: "{{ shell_login_bash }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export DOT_ZSH_COMPLETIONS_DIR="{{ zsh_completions_dir }}"
      export DOT_ZSH_DYNRC_DIR="{{ zsh_dynrc_dir }}"
      export DOT_ZSH_FUNCTIONS_DIR="{{ zsh_functions_dir }}"
      export DOT_ZSH_PLUGINS_DIR="{{ zsh_plugins_dir }}"
      export DOT_ZSH_SCRIPTS_DIR="{{ zsh_scripts_dir }}"

      export DOT_ZSH_ZPROFILE="{{ zsh_zprofile }}"

      export DOT_ZSH_ZSHRC_INTERACTIVE="{{ zsh_zshrc_interactive }}"
      export DOT_ZSH_ZSHRC="{{ zsh_zshrc }}"
      export DOT_ZSH_ZSHRC_COMPINIT_PRE="{{ zsh_zshrc_compinit_pre }}"
      export DOT_ZSH_ZSHRC_COMPINIT_POST="{{ zsh_zshrc_compinit_post }}"

      export DOT_ZSH_ALIASES="{{ zsh_aliases }}"

      export DOT_ZSH_ZLOGIN="{{ zsh_zlogin }}"

      export DOT_ZSH_ZLOGOUT="{{ zsh_zlogout }}"

      export DOT_ZSH_P10K="{{ zsh_p10k }}"

- name: "{{ user }} : shell : Add block to shell_login_fish"
  blockinfile:
    path: "{{ shell_login_fish }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      set -x DOT_ZSH_COMPLETIONS_DIR "{{ zsh_completions_dir }}"
      set -x DOT_ZSH_DYNRC_DIR "{{ zsh_dynrc_dir }}"
      set -x DOT_ZSH_FUNCTIONS_DIR "{{ zsh_functions_dir }}"
      set -x DOT_ZSH_PLUGINS_DIR "{{ zsh_plugins_dir }}"
      set -x DOT_ZSH_SCRIPTS_DIR "{{ zsh_scripts_dir }}"

      set -x DOT_ZSH_ZPROFILE "{{ zsh_zprofile }}"

      set -x DOT_ZSH_ZSHRC_INTERACTIVE "{{ zsh_zshrc_interactive }}"
      set -x DOT_ZSH_ZSHRC "{{ zsh_zshrc }}"
      set -x DOT_ZSH_ZSHRC_COMPINIT_PRE "{{ zsh_zshrc_compinit_pre }}"
      set -x DOT_ZSH_ZSHRC_COMPINIT_POST "{{ zsh_zshrc_compinit_post }}"

      set -x DOT_ZSH_ALIASES "{{ zsh_aliases }}"

      set -x DOT_ZSH_ZLOGIN "{{ zsh_zlogin }}"

      set -x DOT_ZSH_ZLOGOUT "{{ zsh_zlogout }}"

      set -x DOT_ZSH_P10K "{{ zsh_p10k }}"

- name: "{{ user }} : shell : Add block to shell_login_zsh"
  blockinfile:
    path: "{{ shell_login_zsh }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      export DOT_ZSH_COMPLETIONS_DIR="{{ zsh_completions_dir }}"
      export DOT_ZSH_DYNRC_DIR="{{ zsh_dynrc_dir }}"
      export DOT_ZSH_FUNCTIONS_DIR="{{ zsh_functions_dir }}"
      export DOT_ZSH_PLUGINS_DIR="{{ zsh_plugins_dir }}"
      export DOT_ZSH_SCRIPTS_DIR="{{ zsh_scripts_dir }}"

      export DOT_ZSH_ZPROFILE="{{ zsh_zprofile }}"

      export DOT_ZSH_ZSHRC_INTERACTIVE="{{ zsh_zshrc_interactive }}"
      export DOT_ZSH_ZSHRC="{{ zsh_zshrc }}"
      export DOT_ZSH_ZSHRC_COMPINIT_PRE="{{ zsh_zshrc_compinit_pre }}"
      export DOT_ZSH_ZSHRC_COMPINIT_POST="{{ zsh_zshrc_compinit_post }}"

      export DOT_ZSH_ALIASES="{{ zsh_aliases }}"

      export DOT_ZSH_ZLOGIN="{{ zsh_zlogin }}"

      export DOT_ZSH_ZLOGOUT="{{ zsh_zlogout }}"

      export DOT_ZSH_P10K="{{ zsh_p10k }}"


# ------------------------------------------------------------------------------


- name: "{{ user }} : Delete files"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - $HOME/.zshrc
    - $HOME/.zsh_history
    - $HOME/.zcompdump

- name: "{{ user }} : Place $HOME/.zshenv"
  ansible.builtin.copy:
    dest: $HOME/.zshenv
    content: ZDOTDIR=$HOME/.config/zsh

- name: "{{ user }} : Place $HOME/.config/zsh/.zshenv"
  ansible.builtin.copy:
    src: .zshenv
    dest: $HOME/.config/zsh/.zshenv

- name: "{{ user }} : Place $HOME/.config/zsh/.zprofile"
  ansible.builtin.copy:
    src: .zprofile
    dest: $HOME/.config/zsh/.zprofile

- name: "{{ user }} : Place $HOME/.config/zsh/.zshrc"
  ansible.builtin.copy:
    src: .zshrc
    dest: $HOME/.config/zsh/.zshrc

- name: "{{ user }} : Place $HOME/.config/zsh/.zlogin"
  ansible.builtin.copy:
    src: .zlogin
    dest: $HOME/.config/zsh/.zlogin

- name: "{{ user }} : Place $HOME/.config/zsh/.zlogout"
  ansible.builtin.copy:
    src: .zlogout
    dest: $HOME/.config/zsh/.zlogout


# ------------------------------------------------------------------------------


- name: "{{ user }} : Place $HOME/.config/zsh/.p10k.zsh"
  ansible.builtin.copy:
    src: .p10k.zsh
    dest: $HOME/.config/zsh/.p10k.zsh

- name: "{{ user }} : Place $HOME/.config/zsh/p10k-pre.zsh"
  ansible.builtin.copy:
    src: p10k-pre.zsh
    dest: $HOME/.config/zsh/p10k-pre.zsh

- name: "{{ user }} : Place $HOME/.config/zsh/p10k-post.zsh"
  ansible.builtin.copy:
    src: p10k-post.zsh
    dest: $HOME/.config/zsh/p10k-post.zsh


# ------------------------------------------------------------------------------


- name: "{{ user }} : Place scripts"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ zsh_scripts_dir }}/{{ item | basename }}"
    mode: u=rwx,g=r,o=r
    force: true
  with_fileglob: scripts/*.zsh
  changed_when: false

- name: "{{ user }} : Create Crontab entry for zcompile-zcompdump.zsh"
  ansible.builtin.cron:
    name: zsh-zcompile-zcompdump
    special_time: hourly
    job: "nice -n 19 {{ zsh_scripts_dir }}/zcompile-zcompdump.zsh"

- name: "{{ user }} : Create Crontab entry for zcompile-stuff.zsh"
  ansible.builtin.cron:
    name: zsh-zcompile-stuff
    special_time: hourly
    job: "nice -n 19 {{ zsh_scripts_dir }}/zcompile-zcompdump.zsh"
