- name: Import role trallnag.aws_cli
  ansible.builtin.import_role:
    name: trallnag.aws_cli
  vars:
    aws_cli_version: latest

- name: Add block to { bash_bashrc }
  ansible.builtin.blockinfile:
    path: "{{ bash_bashrc }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      complete -C /usr/local/bin/aws_completer aws

- name: Add block to { zsh_zshrc_compinit_post }
  ansible.builtin.blockinfile:
    path: "{{ zsh_zshrc_compinit_post }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      complete -C /usr/local/bin/aws_completer aws

- name: Import role trallnag.aws_ssm_plugin
  ansible.builtin.import_role:
    name: trallnag.aws_ssm_plugin
  vars:
    aws_ssm_plugin_version: latest
