"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$conda\
$python\
$cmd_duration\
$line_break\
$character\
"""

right_format = ""

[directory]
read_only = " 󰌾 "
truncation_length = 10
truncate_to_repo = false
truncation_symbol = "…/"
style = "fg:#0C8696 bold"
repo_root_style = "fg:#4A86B4 bold"

[git_branch]
symbol = " "

[git_commit]
tag_symbol = ' 󰓹 '

[conda]
symbol = "󱔎 "

[python]
symbol = " "
