- name: Determine win_env_userprofile
  ansible.builtin.command: wslvar USERPROFILE
  register: task
  changed_when: false

- name: Set win_env_userprofile
  ansible.builtin.set_fact:
    win_env_userprofile: "{{ task.stdout }}"

- name: Print win_env_userprofile
  ansible.builtin.debug:
    var: win_env_userprofile

# ------------------------------------------------------------------------------

- name: Determine win_home
  ansible.builtin.command: wslpath "{{ win_env_userprofile }}"
  register: task
  changed_when: false

- name: Set win_home
  ansible.builtin.set_fact:
    win_home: "{{ task.stdout }}"

- name: Print win_home
  ansible.builtin.debug:
    var: win_home

# ------------------------------------------------------------------------------

- name: "bash : Windows Terminal split pane same directory"
  blockinfile:
    path: "{{ bash_bashrc }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: 4b92c219-046b-4993-80b9-7ec7f85667d0"
    block: |
      PROMPT_COMMAND=${PROMPT_COMMAND:+"$PROMPT_COMMAND; "}'printf "\e]9;9;%s\e\\" "$(wslpath -w "$PWD")"'

- name: "zsh : Windows Terminal split pane same directory"
  blockinfile:
    path: "{{ zsh_zshrc }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: 4330518c-ab27-4f89-a939-16e0c2c4918f"
    block: |
      keep_current_path() {
        printf "\e]9;9;%s\e\\" "$(wslpath -w "$PWD")"
      }
      precmd_functions+=(keep_current_path)
