- name: Install PowerShell module
  ansible.builtin.shell:
    executable: pwsh.exe
    cmd: "{{ lookup('ansible.builtin.file', 'install-powershell-module.ps1') }}"
  register: task
  changed_when: "'status=changed' in task.stdout"

- name: Get installed packages
  ansible.builtin.shell:
    executable: pwsh.exe
    cmd: "{{ lookup('ansible.builtin.file', 'get-installed-packages.ps1') }}"
  register: get_installed_packages
  changed_when: false

- name: Set installed packages fact
  ansible.builtin.set_fact:
    windows_winget_installed_packages: "{{ get_installed_packages.stdout_lines }}"
