- name: Install module WinGetClient
  ansible.builtin.command:
    argv: "{{ cmd + [script] }}"
  vars:
    cmd: [pwsh.exe, -NoLogo, -NoProfile, -NonInteractive, -Command]
    script: "{{ lookup('ansible.builtin.file', 'install-module-client.ps1') }}"
  register: task
  changed_when: "'status=changed' in task.stdout"

- name: Get installed packages
  ansible.builtin.command:
    argv: "{{ cmd + [script] }}"
  vars:
    cmd: [pwsh.exe, -NoLogo, -NoProfile, -NonInteractive, -Command]
    script: "{{ lookup('ansible.builtin.file', 'get-installed-packages.ps1') }}"
  register: get_installed_packages
  changed_when: "'status=changed' in task.stdout"

- name: Set installed packages fact
  ansible.builtin.set_fact:
    windows_winget_installed_packages: "{{ get_installed_packages.stdout_lines }}"
