- name: Create shortcut
  ansible.builtin.command:
    argv: "{{ cmd + [script] }}"
  vars:
    cmd: [pwsh.exe, -NoLogo, -NoProfile, -NonInteractive, -Command]
    script: "{{ lookup('ansible.builtin.file', 'create-shortcut.ps1') }}"
  changed_when: false
